test_user/myproj/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^index/', include('users.urls', namespace="index")),
    # re_path(r'^log/', include('users.urls', namespace="index")),
]

test_user/users/urls.py
from django.urls import re_path

from . import views

app_name = "index"

urlpatterns = [
    re_path(r'^$', views.UsersView.as_view(), name='index'),
    re_path(r'^login', views.block_login_page, name='login'),
    re_path(r'^logout', views.user_logout, name='logout'),
    re_path(r'^loggedin', views.get_current_user, name='loggedin'),
    re_path(r'^registration', views.register_user, name='registration'),
    re_path(r'^profile', views.profile, name='profile'),
    re_path(r'^log', views.Log.as_view(), name='log'),
    
]

test_user/my_app/models.py
from django.db import models

# Create your models here.

test_user/users/models.py
from django.db import models
from django.contrib.auth.models import User


class Users(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.IntegerField(default=0)
    photo = models.ImageField(blank=True, upload_to="static/user_photo")

    def __str__(self):
        return self.user.username

    def is_adult(self):
        return self.age >= 18

test_user/users/forms.py
from PIL import Image
from django.forms import ImageField
from django.contrib.auth.models import User
from .models import Users
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ModelForm


class FormControlMixin(object):
    def __init__(self, *args, **kwargs):
        super(FormControlMixin, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})


class AuthForm(FormControlMixin, AuthenticationForm):
    pass


class RegistrationForm(FormControlMixin, UserCreationForm):
    photo = ImageField(required=False)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'photo',
                  'password1', 'password2']

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=commit)
        new_user = Users(user=user)
        if self.cleaned_data['photo']:
            new_user.photo = self.cleaned_data['photo']
            image = Image.open(new_user.photo)
            image.save(new_user.photo)
        if commit:
            new_user.save()
        return new_user


class ProfileForm(FormControlMixin, ModelForm):
    photo = ImageField(required=False)

    class Meta:
        model = User
        fields = ['photo', 'first_name', 'last_name']

    def save(self, commit=True):
        user = super(ProfileForm, self).save(commit=commit)
        update_user = Users.objects.get(user=user)
        if self.cleaned_data['photo']:
            update_user.photo = self.cleaned_data['photo']
            image = Image.open(update_user.photo)
            image.save(update_user.photo)
        if commit:
            update_user.save()

        return update_user

test_user/my_app/views.py
from django.shortcuts import render

# Create your views here.

test_user/users/views.py
import logging
import json

from django.contrib.auth import logout
from django.contrib.auth.views import LoginView
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, View

from .forms import RegistrationForm, ProfileForm, AuthForm
from .models import Users
from myproj.celery_app import app
from users.tasks import deactivate_user

logger = logging.getLogger('custom_logger')

def get_current_user(request):
    return render(request, 'users/loggedin.html')


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/index/')

def block_login_page(request):
    if request.user.is_authenticated:
        logger.debug("User %s is authenticated", request.user)
        return HttpResponseRedirect('/index/')
    else:
        logger.info("User is not authenticated")
        return LoginView(**{"request": request, "template_name":'users/login.html',
                            "authentication_form": AuthForm}).post(request)


def register_user(request):
    if request.POST:
        form = RegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            logger.debug("New user registered.")
            form.save()
            return HttpResponseRedirect(reverse_lazy('index:index'))
        else:
            return render(request, 'users/registration.html', context={
                'form': form
            })
    else:
        return render(request, 'users/registration.html', context={
            'form': RegistrationForm()
        })


@login_required(login_url='/index/login/')
def profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES,
                              instance=request.user)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse_lazy('index:index'))
        else:
            return render(request, 'users/profile.html', context={
                'form': form
            })
    else:
        return render(request, 'users/profile.html', context={
            'form': ProfileForm(instance=request.user),
        })


class UsersView(ListView):
    template_name = 'users/index.html'
    context_object_name = 'users_list'
    model = Users

    def get_context_data(self, *, object_list=None, **kwargs):
        context_data = super().get_context_data(object_list=object_list, **kwargs)
        logger.debug("context: %s", context_data['page_obj'])
        result = app.send_task('square_root', args=(4,))
        print(result.ready())
        print(result.ready())
        print(result.get(timeout=5))
        # result = deactivate_user.apply_async()
        # print(result.ready())
        return context_data


class Log(View):
    def post(self, request):
        print (request.POST.get('log', False))
        return render(request, 'users/loggedin.html')

test_user/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Users LightIT Academy</title>
    {% load static %}

<script src="https://code.jquery.com/jquery-1.11.3.min.js" ></script>
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="{% static 'css/style_base.css' %}"/>

        <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">

    <link rel="stylesheet" href="{% static 'css/creative.css' %}" type="text/css">

    {% block links %}
    {% endblock %}
</head>
<div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse"
                        data-target=".navbar-collapse">
                    <span class="glyphicon glyphicon-align-justify"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse">
                <ul id="menu" class="nav navbar-nav">
                 {% for k, v in menus.items %}

                    <li {% if k == title %} class="active" {% endif %}>
                            {% if k == 'LogIn' %}
                                <a href="{{ v }}?next={{ request.path }}">{{ k }}</a>
                            {% else %}
                                <a  href="{{ v }}">{{ k }}</a>
                            {% endif %}
                    </li>
                    {% endfor %}
                </ul>

                <p class="navbar-text navbar-right">

                        {% block user_name %}
                        {% if user.is_authenticated %}
                            <a href="#" class="navbar-link">
                                {{ user.username }}
                            </a>
                        {% else %}
                            <a href="#myLoginForm" class="btn btn-dafeault" role="button"
                               data-toggle="modal">
                                    Login
                            </a>
                            <a href="{% url 'index:registration' %}" class="btn btn-dafeault">
                                    Registration
                            </a>
                        {% endif %}
                        {% endblock %}
                </p>

            </div>
        </div>
</div>
<div id="body_div" class="container-fluid">
    {% block body_app %}
    {% endblock %}
</div>
<div id="foot" class="panel-footer">
    <footer>
        {% now "Y" %}
    </footer>
</div>

<div class="modal fade" id="myLoginForm" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">x</button>
                <h4>Login</h4>
            </div>
            <form method="post" action="{% url 'index:login' %}?next={{request.path}}">
                {% csrf_token %}
                 <div class="modal-body">
                    {{ form_for_login.as_p }}
                 </div>
                <div class="modal-footer">
                    <input type="submit" value="Login"/>
                </div>
            </form>
        </div>
    </div>
</div>

</body>
</html>

test_user/templates/users/index.html
{% extends 'base_template.html' %}
{% block body_app %}
    {% for user in users_list %}
        {% if user.photo %}
            <img src="/{{ user.photo }}"/>
        {% else %}
            {% load static %}
            <img src="{% static 'image/default.png' %}"/>
        {% endif %}
        {{ user.user.username }}
        {{ user.user.first_name }}
        {{ user.user.last_name }}
        {{ user.user.email }}
        <br/>
    {% endfor %}
{% endblock %}

test_user/templates/users/loggedin.html
{% extends 'base_template.html' %}
{% block body_app %}
    {% if user.is_authenticated %}
        <p>You are loggedin</p>
    {% endif %}
{% endblock %}

test_user/templates/users/login.html
{% extends 'base_template.html' %}
 {% block body_app %}
    <div class="col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4">
        <form method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-default" value="Login" />
        </form>
        <a href="/index/registration/" class="btn btn-default">
            Registration
        </a>
    </div>
{% endblock %}

test_user/templates/users/profile.html
{% extends 'base_template.html' %}
{% block body_app %}
    <div class="col-sm-4 col-sm-offset-3 col-md-4 col-md-offset-3">
        <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {% if user.users.photo %}
                <img src="/{{ user.users.photo }}" />
            {% else %}
                {% load static %}
                <img src="{% static 'image/default.png' %}"/>
            {% endif %}
            {% for field in form %}
                <label>{{ field.label }} :</label>
                {{ field }}
                <br/>
            {% endfor %}

            <input type="submit" class="btn btn-default" value="Change" />

        </form>
    </div>

{% endblock %}

test_user/templates/users/registration.html
{% extends 'base_template.html' %}
{% block links %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/registration.css' %}" />
{% endblock %}
{% block body_app %}
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-3">
        <form id="my_form" method="post" enctype="multipart/form-data"
                action="{% url 'index:registration' %}">
            {% csrf_token %}
            {% for item in form %}
                <div class="form-group
                        {% if item.errors %} has-error {% endif %} ">
                        <strong>{{ item.label }} :</strong>

                        <p>
                            {{ item }}

                            <span class="help-block">
                                {% if item.errors %}
                                    {% for error in item.errors %}
                                           {{ error }}
                                    {% endfor %}
                                {% else %}
                                    {{ item.help_text }}
                                {% endif %}
                            </span>
                        </p>
                </div>
            {% endfor %}
            <div>
                 <input type="submit" class="btn btn-default" value="Registrate" />
            </div>
        </form>
    </div>
{% endblock %}